-- Databricks notebook source
-- MAGIC %md
-- MAGIC # Genie Observability — Bootstrap
-- MAGIC Creates the target schema and Delta tables for the observability hub.
-- MAGIC Run once per environment, idempotent.

-- COMMAND ----------

-- DBTITLE 1,Pipeline Parameters
# Accept parameters from 00_config orchestrator (with defaults for standalone runs)
_widget_names = [w.name for w in dbutils.widgets.getAll()]
TARGET_CATALOG = dbutils.widgets.get("target_catalog") if "target_catalog" in _widget_names else "serverless_stable_h7wanf_catalog"
TARGET_SCHEMA = dbutils.widgets.get("target_schema") if "target_schema" in _widget_names else "genie_observability"
TARGET_PREFIX = f"{TARGET_CATALOG}.{TARGET_SCHEMA}"
WAREHOUSE_ID = dbutils.widgets.get("warehouse_id") if "warehouse_id" in _widget_names else "4047b28d66a51bdc"
WORKSPACE_ID = dbutils.widgets.get("workspace_id") if "workspace_id" in _widget_names else "7474657986130378"
LOOKBACK_DAYS = int(dbutils.widgets.get("lookback_days")) if "lookback_days" in _widget_names else 90
SPACE_IDS_STR = dbutils.widgets.get("space_ids") if "space_ids" in _widget_names else ""
SPACE_IDS = SPACE_IDS_STR.split(",") if SPACE_IDS_STR else []

# Bridge for SQL cells that use :catalog / :schema parameter syntax
dbutils.widgets.text("catalog", TARGET_CATALOG, "Catalog")
dbutils.widgets.text("schema", TARGET_SCHEMA, "Schema")

print(f"Config: {TARGET_PREFIX} | Warehouse: {WAREHOUSE_ID} | Spaces: {len(SPACE_IDS)}")

-- COMMAND ----------

-- Use bundle variables (injected via widget or parameter)
-- In SQL tasks these come from the job parameters
CREATE SCHEMA IF NOT EXISTS IDENTIFIER(:catalog || '.' || :schema)
COMMENT 'Genie Observability Hub — conversation content, cost attribution, and quality metrics';

-- COMMAND ----------

CREATE TABLE IF NOT EXISTS IDENTIFIER(:catalog || '.' || :schema || '.genie_spaces') (
  space_id              STRING        NOT NULL COMMENT 'Genie Space UUID',
  workspace_id          STRING        NOT NULL COMMENT 'Workspace ID where space lives',
  display_name          STRING        COMMENT 'Human-readable space name',
  description           STRING        COMMENT 'Space description/instructions',
  warehouse_id          STRING        COMMENT 'SQL warehouse bound to space',
  table_identifiers     ARRAY<STRING> COMMENT 'Tables configured in the space',
  created_by            STRING        COMMENT 'Creator email',
  created_at            TIMESTAMP     COMMENT 'Space creation time',
  updated_at            TIMESTAMP     COMMENT 'Last update time',
  harvested_at          TIMESTAMP     NOT NULL COMMENT 'When this row was last refreshed',
  CONSTRAINT pk_spaces PRIMARY KEY (space_id, workspace_id)
)
USING DELTA
COMMENT 'Metadata for all Genie Spaces in the workspace'
TBLPROPERTIES ('delta.enableChangeDataFeed' = 'true');

-- COMMAND ----------

CREATE TABLE IF NOT EXISTS IDENTIFIER(:catalog || '.' || :schema || '.genie_conversations') (
  conversation_id       STRING        NOT NULL COMMENT 'Conversation thread UUID',
  space_id              STRING        NOT NULL COMMENT 'Parent space UUID',
  workspace_id          STRING        NOT NULL COMMENT 'Workspace ID',
  user_email            STRING        COMMENT 'User who started the conversation',
  title                 STRING        COMMENT 'Conversation title (user-set or auto)',
  created_at            TIMESTAMP     COMMENT 'Conversation start time',
  message_count         INT           COMMENT 'Number of messages in thread',
  last_message_at       TIMESTAMP     COMMENT 'Most recent message timestamp',
  harvested_at          TIMESTAMP     NOT NULL COMMENT 'When this row was last refreshed',
  CONSTRAINT pk_conversations PRIMARY KEY (conversation_id, space_id)
)
USING DELTA
COMMENT 'Conversation threads across all Genie Spaces'
TBLPROPERTIES ('delta.enableChangeDataFeed' = 'true');

-- COMMAND ----------

CREATE TABLE IF NOT EXISTS IDENTIFIER(:catalog || '.' || :schema || '.genie_messages') (
  message_id            STRING        NOT NULL COMMENT 'Message UUID',
  conversation_id       STRING        NOT NULL COMMENT 'Parent conversation UUID',
  space_id              STRING        NOT NULL COMMENT 'Parent space UUID',
  workspace_id          STRING        NOT NULL COMMENT 'Workspace ID',
  user_email            STRING        COMMENT 'User who sent this message',
  role                  STRING        COMMENT 'USER or ASSISTANT',
  -- Content fields (the high-value data not in system tables)
  user_query            STRING        COMMENT 'Original natural-language question',
  response_text         STRING        COMMENT 'Genie natural-language response',
  generated_sql         STRING        COMMENT 'SQL generated by Genie',
  -- Status & thinking trace
  status                STRING        COMMENT 'Final status: COMPLETED, FAILED, CANCELLED, etc.',
  state_transitions     ARRAY<STRING> COMMENT 'Ordered state names: asking_ai, fetching_metadata, executing_query, etc.',
  error_message         STRING        COMMENT 'Error details if status=FAILED',
  -- Timing
  created_at            TIMESTAMP     COMMENT 'Message creation time',
  completed_at          TIMESTAMP     COMMENT 'When response was fully generated',
  duration_ms           LONG          COMMENT 'Total response time in milliseconds',
  -- Feedback
  feedback_rating       STRING        COMMENT 'User feedback: thumbs_up, thumbs_down, null',
  feedback_comment      STRING        COMMENT 'Optional feedback text',
  -- Attachments
  has_visualization     BOOLEAN       COMMENT 'Whether response included a chart',
  has_table_result      BOOLEAN       COMMENT 'Whether response included tabular data',
  result_row_count      LONG          COMMENT 'Number of rows in query result',
  -- Harvesting metadata
  harvested_at          TIMESTAMP     NOT NULL COMMENT 'When this row was last refreshed',
  CONSTRAINT pk_messages PRIMARY KEY (message_id)
)
USING DELTA
COMMENT 'Full message content: user questions, Genie responses, generated SQL, thinking states'
TBLPROPERTIES ('delta.enableChangeDataFeed' = 'true');

-- COMMAND ----------

CREATE TABLE IF NOT EXISTS IDENTIFIER(:catalog || '.' || :schema || '.genie_query_executions') (
  statement_id          STRING        NOT NULL COMMENT 'Query history statement ID',
  workspace_id          STRING        NOT NULL COMMENT 'Workspace ID',
  executed_by           STRING        COMMENT 'User or SP that ran the query',
  client_application    STRING        COMMENT 'Genie client app identifier',
  statement_text        STRING        COMMENT 'Full SQL statement text',
  execution_status      STRING        COMMENT 'FINISHED, FAILED, CANCELED',
  error_message         STRING        COMMENT 'Error if failed',
  total_duration_ms     LONG          COMMENT 'Total execution time',
  execution_duration_ms LONG          COMMENT 'Pure execution time',
  compilation_duration_ms LONG        COMMENT 'Optimization/compilation time',
  read_bytes            LONG          COMMENT 'Bytes read from storage',
  read_rows             LONG          COMMENT 'Rows scanned',
  produced_rows         LONG          COMMENT 'Rows returned',
  start_time            TIMESTAMP     COMMENT 'Query start time',
  end_time              TIMESTAMP     COMMENT 'Query end time',
  harvested_at          TIMESTAMP     NOT NULL COMMENT 'When this row was last refreshed',
  CONSTRAINT pk_queries PRIMARY KEY (statement_id)
)
USING DELTA
COMMENT 'SQL queries generated and executed by Genie, from system.query.history'
TBLPROPERTIES ('delta.enableChangeDataFeed' = 'true');

-- COMMAND ----------

CREATE TABLE IF NOT EXISTS IDENTIFIER(:catalog || '.' || :schema || '.genie_cost_attribution') (
  usage_date            DATE          NOT NULL COMMENT 'Day of usage',
  workspace_id          STRING        NOT NULL COMMENT 'Workspace ID',
  user_email            STRING        COMMENT 'User email (from custom_tags.Owner)',
  user_id               STRING        COMMENT 'User UUID (from identity_metadata.run_as)',
  sku_name              STRING        COMMENT 'Billing SKU name',
  total_dbus            DECIMAL(20,6) COMMENT 'Total DBUs consumed',
  estimated_cost_usd    DECIMAL(20,6) COMMENT 'Estimated cost (DBUs * list price)',
  harvested_at          TIMESTAMP     NOT NULL COMMENT 'When this row was last refreshed',
  CONSTRAINT pk_cost PRIMARY KEY (usage_date, workspace_id, user_email, sku_name)
)
USING DELTA
COMMENT 'Per-user daily Genie token cost attribution'
TBLPROPERTIES ('delta.enableChangeDataFeed' = 'true');

-- COMMAND ----------

-- Watermark table to track incremental harvesting state
CREATE TABLE IF NOT EXISTS IDENTIFIER(:catalog || '.' || :schema || '.harvest_watermarks') (
  source_name           STRING        NOT NULL COMMENT 'Source identifier: audit_log, query_history, billing, space:{id}',
  high_watermark        TIMESTAMP     NOT NULL COMMENT 'Latest event time successfully harvested',
  rows_harvested        LONG          COMMENT 'Rows written in last run',
  updated_at            TIMESTAMP     NOT NULL COMMENT 'When watermark was last updated',
  CONSTRAINT pk_watermarks PRIMARY KEY (source_name)
)
USING DELTA
COMMENT 'Incremental harvesting state — tracks last-processed timestamp per source';

-- COMMAND ----------

-- DBTITLE 1,Pre-aggregated: genie_daily_metrics
CREATE TABLE IF NOT EXISTS IDENTIFIER(:catalog || '.' || :schema || '.genie_daily_metrics') (
  metric_date           DATE          NOT NULL COMMENT 'Day of metrics',
  workspace_id          STRING        NOT NULL COMMENT 'Workspace ID',
  message_count         BIGINT        COMMENT 'Total messages that day',
  conversation_count    BIGINT        COMMENT 'Conversations active that day',
  unique_users          BIGINT        COMMENT 'Distinct users that day',
  avg_duration_ms       DOUBLE        COMMENT 'Mean response time',
  p50_duration_ms       DOUBLE        COMMENT 'Median response time',
  p95_duration_ms       DOUBLE        COMMENT '95th percentile response time',
  success_rate          DOUBLE        COMMENT 'COMPLETED / total messages',
  sql_generation_rate   DOUBLE        COMMENT 'Messages with generated SQL / total',
  total_dbus            DOUBLE        COMMENT 'Sum DBUs from cost_attribution',
  computed_at           TIMESTAMP     NOT NULL COMMENT 'When this row was last computed',
  CONSTRAINT pk_daily_metrics PRIMARY KEY (metric_date, workspace_id)
)
USING DELTA
COMMENT 'Pre-aggregated daily metrics for fast dashboard rendering'
TBLPROPERTIES ('delta.enableChangeDataFeed' = 'true');

-- COMMAND ----------

-- DBTITLE 1,Pre-aggregated: genie_space_metrics
CREATE TABLE IF NOT EXISTS IDENTIFIER(:catalog || '.' || :schema || '.genie_space_metrics') (
  space_id              STRING        NOT NULL COMMENT 'Genie Space UUID',
  display_name          STRING        COMMENT 'Space display name',
  total_messages        BIGINT        COMMENT 'All-time message count',
  total_conversations   BIGINT        COMMENT 'All-time conversation count',
  unique_users          BIGINT        COMMENT 'Distinct users ever',
  avg_duration_ms       DOUBLE        COMMENT 'Mean response time across all messages',
  p95_duration_ms       DOUBLE        COMMENT '95th percentile response time',
  success_rate          DOUBLE        COMMENT 'COMPLETED / total messages',
  sql_generation_rate   DOUBLE        COMMENT 'Messages with generated SQL / total',
  last_activity_at      TIMESTAMP     COMMENT 'Most recent message timestamp',
  computed_at           TIMESTAMP     NOT NULL COMMENT 'When this row was last computed',
  CONSTRAINT pk_space_metrics PRIMARY KEY (space_id)
)
USING DELTA
COMMENT 'Pre-aggregated per-space metrics for fast dashboard rendering'
TBLPROPERTIES ('delta.enableChangeDataFeed' = 'true');

-- COMMAND ----------

-- DBTITLE 1,Pre-aggregated: genie_user_metrics
CREATE TABLE IF NOT EXISTS IDENTIFIER(:catalog || '.' || :schema || '.genie_user_metrics') (
  user_email            STRING        NOT NULL COMMENT 'User email',
  workspace_id          STRING        NOT NULL COMMENT 'Workspace ID',
  total_messages        BIGINT        COMMENT 'All-time message count',
  total_conversations   BIGINT        COMMENT 'All-time conversation count',
  spaces_used           BIGINT        COMMENT 'Distinct spaces interacted with',
  avg_duration_ms       DOUBLE        COMMENT 'Mean response time',
  success_rate          DOUBLE        COMMENT 'COMPLETED / total messages',
  total_dbus            DOUBLE        COMMENT 'Lifetime DBU cost',
  first_seen            TIMESTAMP     COMMENT 'First message timestamp',
  last_seen             TIMESTAMP     COMMENT 'Most recent message timestamp',
  computed_at           TIMESTAMP     NOT NULL COMMENT 'When this row was last computed',
  CONSTRAINT pk_user_metrics PRIMARY KEY (user_email, workspace_id)
)
USING DELTA
COMMENT 'Pre-aggregated per-user metrics for fast dashboard rendering'
TBLPROPERTIES ('delta.enableChangeDataFeed' = 'true');
