# Databricks notebook source
# MAGIC %md
# MAGIC # Genie Observability — Alerts & Retention
# MAGIC
# MAGIC Runs after the harvester to:
# MAGIC 1. Detect anomalies (failure spikes, cost spikes, latency degradation)
# MAGIC 2. Write alert events to a table (for dashboard + email/Slack integration)
# MAGIC 3. Enforce data retention policy (purge old data)
# MAGIC 4. Compute FAQ detection (most common questions)
# MAGIC 5. Calculate SLA metrics (response time percentiles by space)

# COMMAND ----------

# DBTITLE 1,Pipeline Parameters
import json
from datetime import datetime, timedelta, timezone
from databricks.sdk import WorkspaceClient

# Accept parameters from 00_config orchestrator (with defaults for standalone runs)
_widget_names = [w.name for w in dbutils.widgets.getAll()]
TARGET_CATALOG = dbutils.widgets.get("target_catalog") if "target_catalog" in _widget_names else "serverless_stable_h7wanf_catalog"
TARGET_SCHEMA = dbutils.widgets.get("target_schema") if "target_schema" in _widget_names else "genie_observability"
TARGET_PREFIX = f"{TARGET_CATALOG}.{TARGET_SCHEMA}"
WAREHOUSE_ID = dbutils.widgets.get("warehouse_id") if "warehouse_id" in _widget_names else "4047b28d66a51bdc"
WORKSPACE_ID = dbutils.widgets.get("workspace_id") if "workspace_id" in _widget_names else "7474657986130378"
LOOKBACK_DAYS = int(dbutils.widgets.get("lookback_days")) if "lookback_days" in _widget_names else 90
SPACE_IDS_STR = dbutils.widgets.get("space_ids") if "space_ids" in _widget_names else ""
SPACE_IDS = SPACE_IDS_STR.split(",") if SPACE_IDS_STR else []

# Backward compat aliases used throughout this notebook
CATALOG = TARGET_CATALOG
SCHEMA = TARGET_SCHEMA
PREFIX = TARGET_PREFIX

print(f"Config: {TARGET_PREFIX} | Warehouse: {WAREHOUSE_ID} | Spaces: {len(SPACE_IDS)}")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Alert Events Table

# COMMAND ----------

# DBTITLE 1,Cell 4
spark.sql(f"""
CREATE TABLE IF NOT EXISTS {PREFIX}.alert_events (
  alert_id STRING NOT NULL COMMENT 'Unique alert ID',
  alert_type STRING NOT NULL COMMENT 'failure_rate_spike | cost_spike | latency_degradation | new_space_detected',
  severity STRING NOT NULL COMMENT 'critical | warning | info',
  space_id STRING COMMENT 'Affected space (null for workspace-wide alerts)',
  workspace_id STRING COMMENT 'Affected workspace',
  metric_value DOUBLE COMMENT 'Current metric value that triggered the alert',
  threshold_value DOUBLE COMMENT 'Threshold that was exceeded',
  message STRING COMMENT 'Human-readable alert description',
  context STRING COMMENT 'JSON context (affected users, time window, etc.)',
  created_at TIMESTAMP NOT NULL,
  acknowledged_at TIMESTAMP COMMENT 'When an admin acknowledged the alert',
  acknowledged_by STRING COMMENT 'Who acknowledged'
) USING DELTA
COMMENT 'Alert events generated by observability monitors'
""")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Load Thresholds from Config

# COMMAND ----------

def get_config(key: str, default: str = None) -> str:
    try:
        row = spark.sql(f"""
            SELECT config_value FROM {PREFIX}.harvest_config WHERE config_key = '{key}'
        """).first()
        return row.config_value if row else default
    except Exception:
        return default

FAILURE_THRESHOLD = float(get_config("alert_failure_rate_threshold", "0.15"))
COST_SPIKE_THRESHOLD = float(get_config("alert_cost_spike_threshold", "2.0"))
LATENCY_P95_THRESHOLD = int(get_config("alert_latency_p95_threshold_ms", "30000"))
RETENTION_DAYS = int(get_config("retention_days", "90"))

print(f"Thresholds: failure>{FAILURE_THRESHOLD*100}%, cost spike>{COST_SPIKE_THRESHOLD}x, "
      f"latency p95>{LATENCY_P95_THRESHOLD}ms, retention={RETENTION_DAYS}d")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Monitor: Failure Rate Spike (per space, last 24h vs prior 7d)

# COMMAND ----------

# DBTITLE 1,Cell 8
spark.sql(f"""
INSERT INTO {PREFIX}.alert_events (alert_id, alert_type, severity, space_id, workspace_id,
                                    metric_value, threshold_value, message, context, created_at)
WITH recent AS (
  SELECT space_id, workspace_id,
    COUNT(*) AS total,
    SUM(CASE WHEN status = 'FAILED' THEN 1 ELSE 0 END) AS failed
  FROM {PREFIX}.genie_messages
  WHERE created_at >= current_timestamp() - INTERVAL 24 HOURS
    AND role = 'ASSISTANT'
  GROUP BY space_id, workspace_id
  HAVING total >= 5  -- minimum sample
),
baseline AS (
  SELECT space_id,
    SUM(CASE WHEN status = 'FAILED' THEN 1 ELSE 0 END) * 1.0 / COUNT(*) AS baseline_rate
  FROM {PREFIX}.genie_messages
  WHERE created_at BETWEEN current_timestamp() - INTERVAL 8 DAYS
                       AND current_timestamp() - INTERVAL 1 DAY
    AND role = 'ASSISTANT'
  GROUP BY space_id
  HAVING COUNT(*) >= 10
)
SELECT
  uuid(),
  'failure_rate_spike',
  CASE WHEN r.failed * 1.0 / r.total > 0.5 THEN 'critical' ELSE 'warning' END,
  r.space_id,
  r.workspace_id,
  ROUND(r.failed * 1.0 / r.total, 3),
  {FAILURE_THRESHOLD},
  CONCAT('Failure rate ', ROUND(r.failed * 100.0 / r.total, 1), '% in last 24h (', r.failed, '/', r.total, ' messages)'),
  NULL,
  current_timestamp()
FROM recent r
LEFT JOIN baseline b ON r.space_id = b.space_id
WHERE r.failed * 1.0 / r.total > {FAILURE_THRESHOLD}
  AND r.failed * 1.0 / r.total > COALESCE(b.baseline_rate * 1.5, {FAILURE_THRESHOLD})
  -- Deduplicate: don't re-alert if same space alerted in last 24h
  AND NOT EXISTS (
    SELECT 1 FROM {PREFIX}.alert_events ae
    WHERE ae.space_id = r.space_id
      AND ae.alert_type = 'failure_rate_spike'
      AND ae.created_at >= current_timestamp() - INTERVAL 24 HOURS
  )
""")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Monitor: Cost Spike (daily DBUs > 2x 7-day average)

# COMMAND ----------

# DBTITLE 1,Cell 10
spark.sql(f"""
INSERT INTO {PREFIX}.alert_events (alert_id, alert_type, severity, space_id, workspace_id,
                                    metric_value, threshold_value, message, context, created_at)
WITH today_cost AS (
  SELECT workspace_id, user_email,
    SUM(total_dbus) AS today_dbus
  FROM {PREFIX}.genie_cost_attribution
  WHERE usage_date = current_date() - 1  -- yesterday (most recent complete day)
  GROUP BY workspace_id, user_email
),
avg_cost AS (
  SELECT workspace_id, user_email,
    AVG(daily_total) AS avg_daily_dbus
  FROM (
    SELECT workspace_id, user_email, usage_date, SUM(total_dbus) AS daily_total
    FROM {PREFIX}.genie_cost_attribution
    WHERE usage_date BETWEEN current_date() - 8 AND current_date() - 2
    GROUP BY workspace_id, user_email, usage_date
  )
  GROUP BY workspace_id, user_email
  HAVING AVG(daily_total) > 0
)
SELECT
  uuid(),
  'cost_spike',
  CASE WHEN t.today_dbus / a.avg_daily_dbus > 5.0 THEN 'critical' ELSE 'warning' END,
  NULL,
  t.workspace_id,
  ROUND(t.today_dbus, 2),
  ROUND(a.avg_daily_dbus * {COST_SPIKE_THRESHOLD}, 2),
  CONCAT(t.user_email, ': ', ROUND(t.today_dbus, 1), ' DBUs yesterday vs ',
         ROUND(a.avg_daily_dbus, 1), ' avg (',
         ROUND(t.today_dbus / a.avg_daily_dbus, 1), 'x spike)'),
  NULL,
  current_timestamp()
FROM today_cost t
JOIN avg_cost a ON t.workspace_id = a.workspace_id AND t.user_email = a.user_email
WHERE t.today_dbus > a.avg_daily_dbus * {COST_SPIKE_THRESHOLD}
  AND NOT EXISTS (
    SELECT 1 FROM {PREFIX}.alert_events ae
    WHERE ae.alert_type = 'cost_spike'
      AND ae.message LIKE CONCAT(t.user_email, '%')
      AND ae.created_at >= current_timestamp() - INTERVAL 24 HOURS
  )
""")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Monitor: Latency Degradation (p95 > threshold)

# COMMAND ----------

# DBTITLE 1,Cell 12
spark.sql(f"""
INSERT INTO {PREFIX}.alert_events (alert_id, alert_type, severity, space_id, workspace_id,
                                    metric_value, threshold_value, message, context, created_at)
SELECT
  uuid(),
  'latency_degradation',
  'warning',
  space_id,
  workspace_id,
  ROUND(p95_ms, 0),
  {LATENCY_P95_THRESHOLD},
  CONCAT('p95 latency = ', ROUND(p95_ms/1000, 1), 's (threshold: ', {LATENCY_P95_THRESHOLD}/1000, 's)'),
  NULL,
  current_timestamp()
FROM (
  SELECT space_id, workspace_id,
    PERCENTILE(duration_ms, 0.95) AS p95_ms
  FROM {PREFIX}.genie_messages
  WHERE created_at >= current_timestamp() - INTERVAL 24 HOURS
    AND duration_ms IS NOT NULL
    AND role = 'ASSISTANT'
  GROUP BY space_id, workspace_id
  HAVING COUNT(*) >= 10
)
WHERE p95_ms > {LATENCY_P95_THRESHOLD}
  AND NOT EXISTS (
    SELECT 1 FROM {PREFIX}.alert_events ae
    WHERE ae.space_id = space_id
      AND ae.alert_type = 'latency_degradation'
      AND ae.created_at >= current_timestamp() - INTERVAL 24 HOURS
  )
""")

# COMMAND ----------

# MAGIC %md
# MAGIC ## FAQ Detection (most common questions by space)

# COMMAND ----------

spark.sql(f"""
CREATE OR REPLACE TABLE {PREFIX}.faq_patterns AS
WITH normalized_queries AS (
  SELECT
    space_id,
    workspace_id,
    LOWER(TRIM(user_query)) AS query_normalized,
    user_query AS sample_query,
    COUNT(*) AS frequency,
    COUNT(DISTINCT user_email) AS unique_users,
    AVG(CASE WHEN status = 'COMPLETED' THEN 1.0 ELSE 0.0 END) AS success_rate,
    AVG(duration_ms) AS avg_duration_ms
  FROM {PREFIX}.genie_messages
  WHERE role = 'USER'
    AND user_query IS NOT NULL
    AND LENGTH(user_query) > 5
    AND created_at >= current_date() - INTERVAL 30 DAYS
  GROUP BY space_id, workspace_id, LOWER(TRIM(user_query)), user_query
)
SELECT
  space_id,
  workspace_id,
  sample_query,
  frequency,
  unique_users,
  ROUND(success_rate, 3) AS success_rate,
  ROUND(avg_duration_ms, 0) AS avg_duration_ms,
  ROW_NUMBER() OVER (PARTITION BY space_id ORDER BY frequency DESC) AS rank_in_space
FROM normalized_queries
WHERE frequency >= 2
QUALIFY rank_in_space <= 50
""")

faq_count = spark.sql(f"SELECT COUNT(*) FROM {PREFIX}.faq_patterns").first()[0]
print(f"✓ FAQ patterns: {faq_count} entries across all spaces")

# COMMAND ----------

# MAGIC %md
# MAGIC ## SLA Metrics (per space, per day)

# COMMAND ----------

spark.sql(f"""
CREATE OR REPLACE TABLE {PREFIX}.sla_metrics AS
SELECT
  space_id,
  workspace_id,
  DATE(created_at) AS metric_date,
  COUNT(*) AS total_messages,
  SUM(CASE WHEN status = 'COMPLETED' THEN 1 ELSE 0 END) AS completed,
  SUM(CASE WHEN status = 'FAILED' THEN 1 ELSE 0 END) AS failed,
  ROUND(SUM(CASE WHEN status = 'COMPLETED' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 1) AS success_rate_pct,
  ROUND(AVG(duration_ms), 0) AS avg_duration_ms,
  ROUND(PERCENTILE(duration_ms, 0.5), 0) AS p50_duration_ms,
  ROUND(PERCENTILE(duration_ms, 0.95), 0) AS p95_duration_ms,
  ROUND(PERCENTILE(duration_ms, 0.99), 0) AS p99_duration_ms,
  COUNT(DISTINCT user_email) AS unique_users,
  SUM(CASE WHEN feedback_rating = 'POSITIVE' THEN 1 ELSE 0 END) AS positive_feedback,
  SUM(CASE WHEN feedback_rating = 'NEGATIVE' THEN 1 ELSE 0 END) AS negative_feedback
FROM {PREFIX}.genie_messages
WHERE role = 'ASSISTANT'
  AND created_at >= current_date() - INTERVAL 90 DAYS
GROUP BY space_id, workspace_id, DATE(created_at)
""")

sla_days = spark.sql(f"SELECT COUNT(DISTINCT metric_date) FROM {PREFIX}.sla_metrics").first()[0]
print(f"✓ SLA metrics: {sla_days} days of data")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Data Retention: Purge old records

# COMMAND ----------

tables_to_purge = ["genie_messages", "genie_conversations", "genie_query_executions"]

for table in tables_to_purge:
    fqn = f"{PREFIX}.{table}"
    try:
        result = spark.sql(f"""
            DELETE FROM {fqn}
            WHERE harvested_at < current_date() - INTERVAL {RETENTION_DAYS} DAYS
        """)
        deleted = result.first()[0] if result.first() else 0
        if deleted:
            print(f"  🗑️ {table}: purged {deleted} rows older than {RETENTION_DAYS} days")
        else:
            print(f"  ✓ {table}: nothing to purge")
    except Exception as e:
        print(f"  ⚠️ {table}: {e}")

# Vacuum to reclaim storage
for table in tables_to_purge:
    try:
        spark.sql(f"OPTIMIZE {PREFIX}.{table}")
    except Exception:
        pass

# COMMAND ----------

# MAGIC %md
# MAGIC ## Alert Summary

# COMMAND ----------

new_alerts = spark.sql(f"""
SELECT alert_type, severity, COUNT(*) AS count
FROM {PREFIX}.alert_events
WHERE created_at >= current_timestamp() - INTERVAL 24 HOURS
GROUP BY alert_type, severity
ORDER BY CASE severity WHEN 'critical' THEN 1 WHEN 'warning' THEN 2 ELSE 3 END
""")

if new_alerts.count() > 0:
    print("⚠️ Alerts generated in last 24h:")
    new_alerts.display()
else:
    print("✅ No new alerts")
